apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: devshelf-postgres
  namespace: {{ .Values.namespace }}

spec:
  serviceName: devshelf-postgres

  replicas: 1

  selector:
    matchLabels:
      app: devshelf
      tier: postgres

  template:
    metadata:
      labels:
        app: devshelf
        tier: postgres

    spec:
      containers:
        - name: postgres
          image: {{ .Values.postgres.image }}:{{ .Values.postgres.tag }}

          ports:
            - containerPort: 5432

          env:
            # EKS EBS fix: avoid using the root of the mounted volume
            - name: PGDATA
              value: /var/lib/postgresql/data/pgdata

            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: devshelf-config
                  key: POSTGRES_USER

            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: devshelf-config
                  key: POSTGRES_DB

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: devshelf-secrets
                  key: postgres-password

          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data

      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: devshelf-postgres-pvc