apiVersion: v1
kind: Service
metadata:
  name: devshelf-frontend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: devshelf
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer