namespace: devshelf-prod

backend:
  image: smplynithin/devshelf-backend
  tag: latest
  replicas: 2
  port: 8000
  resources:
    requests:
      cpu: "100m"
      memory: "128Mi"
    limits:
      cpu: "500m"
      memory: "512Mi"

frontend:
  image: smplynithin/devshelf-frontend
  tag: latest
  replicas: 2
  port: 80

postgres:
  image: postgres
  tag: 15-alpine
  port: 5432
  storage: 1Gi
  storageClass: standard

redis:
  image: redis
  tag: 7-alpine
  port: 6379

ingress:
  host: devshelf.local

secrets:
  databaseUrl: ""
  redisUrl: ""
  postgresPassword: ""
