apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: devshelf-prod
  name: devshelf-backend-role
rules:
- apiGroups: [""]
  resources: ["secrets","configmaps"]
  verbs: ["get", "list"]
