apiVersion: v1
kind: PersistentVolumeClaim

metadata:
  name: devshelf-postgres-pvc
  namespace: devshelf-prod

spec:
  accessModes:
    - ReadWriteOnce

  resources:
    requests:
      storage: 1Gi

  storageClassName: standard