apiVersion: apps/v1
kind: Deployment
metadata:
  name: devshelf-redis
  namespace: {{ .Values.namespace }}
  labels:
    app: devshelf
    tier: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devshelf
      tier: redis
  template:
    metadata:
      labels:
        app: devshelf
        tier: redis
    spec:
      containers:
        - name: redis
          image: {{ .Values.redis.image }}:{{ .Values.redis.tag }}
          ports:
            - containerPort: {{ .Values.redis.port }}