apiVersion: apps/v1
kind: Deployment
metadata:
  name: devshelf-frontend
  labels:
    app: devshelf
    tier: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devshelf
      tier: frontend
  template:
    metadata:
      labels:
        app: devshelf
        tier: frontend
    spec:
      containers:
        - name: frontend
          image: smplynithin/devshelf-frontend:latest
          ports:
            - containerPort: 80