apiVersion: v1
kind: Service
metadata:
  name: devshelf-frontend
  namespace: devshelf-prod
spec:
  selector:
    app: devshelf
    tier: frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer