apiVersion: v1
kind: Service
metadata:
  name: devshelf-backend
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: devshelf
    tier: backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP