apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: {{ .Values.namespace }}
  name: devshelf-backend
  labels:
    app: devshelf
    tier: backend

spec:
  replicas: {{ .Values.backend.replicas }}

  selector:
    matchLabels:
      app: devshelf
      tier: backend

  template:
    metadata:
      labels:
        app: devshelf
        tier: backend

    spec:
      serviceAccountName: devshelf-backend



      containers:
        - name: backend
          image: {{ .Values.backend.image }}:{{ .Values.backend.tag }}

          resources: 
          {{- toYaml .Values.backend.resources | nindent 12 }}

          ports:
            - containerPort: 8000

          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: devshelf-secrets
                  key: database-url

            - name: REDIS_URL
              valueFrom:
                secretKeyRef:
                  name: devshelf-secrets
                  key: redis-url

          livenessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 10
            periodSeconds: 10
            failureThreshold: 3

          readinessProbe:
            httpGet:
              path: /health
              port: 8000
            initialDelaySeconds: 5
            periodSeconds: 5
            failureThreshold: 3