apiVersion: v1
kind: Secret
metadata:
  name: devshelf-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  database-url: {{ .Values.secrets.databaseUrl }}
  redis-url: {{ .Values.secrets.redisUrl }}
  postgres-password: {{ .Values.secrets.postgresPassword }}
